[package]
name = "task-api"
version = "0.1.0"
edition = "2024"

[dependencies]
api = { path = "api" }
dotenv = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "sync"] }

[build-dependencies]
build-print = "1.0.1"
serde_json = { workspace = true }
api = { path = "api" }
