/* tslint:disable */
/* eslint-disable */
/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTaskData
 */
export interface CreateTaskData {
    /**
     * 
     * @type {string}
     * @memberof CreateTaskData
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskData
     */
    title: string;
}

/**
 * Check if a given object implements the CreateTaskData interface.
 */
export function instanceOfCreateTaskData(value: object): value is CreateTaskData {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreateTaskDataFromJSON(json: any): CreateTaskData {
    return CreateTaskDataFromJSONTyped(json, false);
}

export function CreateTaskDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTaskData {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'title': json['title'],
    };
}

export function CreateTaskDataToJSON(json: any): CreateTaskData {
    return CreateTaskDataToJSONTyped(json, false);
}

export function CreateTaskDataToJSONTyped(value?: CreateTaskData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'title': value['title'],
    };
}

