/* tslint:disable */
/* eslint-disable */
/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTaskData
 */
export interface UpdateTaskData {
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskData
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskData
     */
    title?: string | null;
}

/**
 * Check if a given object implements the UpdateTaskData interface.
 */
export function instanceOfUpdateTaskData(value: object): value is UpdateTaskData {
    return true;
}

export function UpdateTaskDataFromJSON(json: any): UpdateTaskData {
    return UpdateTaskDataFromJSONTyped(json, false);
}

export function UpdateTaskDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTaskData {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function UpdateTaskDataToJSON(json: any): UpdateTaskData {
    return UpdateTaskDataToJSONTyped(json, false);
}

export function UpdateTaskDataToJSONTyped(value?: UpdateTaskData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'title': value['title'],
    };
}

