/* tslint:disable */
/* eslint-disable */
/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTaskData,
  TaskResponse,
  UpdateTaskData,
} from '../models/index';
import {
    CreateTaskDataFromJSON,
    CreateTaskDataToJSON,
    TaskResponseFromJSON,
    TaskResponseToJSON,
    UpdateTaskDataFromJSON,
    UpdateTaskDataToJSON,
} from '../models/index';

export interface CreateTasksRequest {
    createTaskData: CreateTaskData;
}

export interface DeleteTasksRequest {
    id: number;
}

export interface UpdateTasksRequest {
    id: number;
    updateTaskData: UpdateTaskData;
}

/**
 * 
 */
export class TasksApi extends runtime.BaseAPI {

    /**
     * Creates request options for createTasks without sending the request
     */
    async createTasksRequestOpts(requestParameters: CreateTasksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createTaskData'] == null) {
            throw new runtime.RequiredError(
                'createTaskData',
                'Required parameter "createTaskData" was null or undefined when calling createTasks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/tasks`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTaskDataToJSON(requestParameters['createTaskData']),
        };
    }

    /**
     */
    async createTasksRaw(requestParameters: CreateTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskResponse>> {
        const requestOptions = await this.createTasksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskResponseFromJSON(jsonValue));
    }

    /**
     */
    async createTasks(requestParameters: CreateTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskResponse> {
        const response = await this.createTasksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTasks without sending the request
     */
    async deleteTasksRequestOpts(requestParameters: DeleteTasksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteTasks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/tasks/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteTasksRaw(requestParameters: DeleteTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTasksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteTasks(requestParameters: DeleteTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTasksRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getTasks without sending the request
     */
    async getTasksRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/tasks`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getTasksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskResponse>>> {
        const requestOptions = await this.getTasksRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskResponseFromJSON));
    }

    /**
     */
    async getTasks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskResponse>> {
        const response = await this.getTasksRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTasks without sending the request
     */
    async updateTasksRequestOpts(requestParameters: UpdateTasksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateTasks().'
            );
        }

        if (requestParameters['updateTaskData'] == null) {
            throw new runtime.RequiredError(
                'updateTaskData',
                'Required parameter "updateTaskData" was null or undefined when calling updateTasks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/tasks/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTaskDataToJSON(requestParameters['updateTaskData']),
        };
    }

    /**
     */
    async updateTasksRaw(requestParameters: UpdateTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskResponse>> {
        const requestOptions = await this.updateTasksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateTasks(requestParameters: UpdateTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskResponse> {
        const response = await this.updateTasksRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
